excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://RahulShivkumar.github.io
title: Home
email: rahulshivkumar@gmail.com
author: Rahul Shivkumar
description: My awesome new site
paginate: 3
google_analytics: 